packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js-pure
  - esbuild
  - sharp

catalog:
  # FE
  "react": ^19.2.3
  "react-dom": ^19.2.3
  "next": ^15.5.9
  "@rainbow-me/rainbowkit": ^2.2.10
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@vercel/analytics": ^1.6.1
  "lucide-react": ^0.561.0
  "next-themes": ^0.4.6
  "sonner": ^2.0.7
  "tailwindcss": ^4.1.18
  "@tailwindcss/postcss": ^4.1.18
  "jotai": ^2.16.0
  "@t3-oss/env-nextjs": ^0.13.10
  "@sentry/nextjs": ^10.30.0
  "react-hook-form": ^7.68.0
  "@metamask/jazzicon": https://github.com/jmrossy/jazzicon#7a8df28
  "tsup": ^8.5.1
  # BE
  "@mento-protocol/mento-sdk": ^1.17.0
  "pino-pretty": ^13.1.3
  # Shared
  "typescript": ^5.9.3
  "@tanstack/react-query": ^5.90.12
  "@types/node": ^22.14.1
  "concurrently": ^9.2.1
  "eslint": ^9.39.2
  "@eslint/js": ^9.39.2
  "esbuild-plugin-preserve-directives": ^0.0.11
  "eslint-config-prettier": ^10.1.2
  "typescript-eslint": ^8.49.0
  "postcss": ^8.5.6
  "zod": ^4.2.0
  "ethers": ^5.8.0
  "wagmi": ^2.19.5
  "viem": ^2.42.1
