packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js-pure
  - esbuild
  - sharp

catalog:
  # FE
  "react": ^19.1.0
  "react-dom": ^19.1.0
  "next": ^15.5.2
  "@next/eslint-plugin-next": ^15.3.0
  "@radix-ui/react-accordion": ^1.2.11
  "@radix-ui/react-checkbox": ^1.3.2
  "@radix-ui/react-collapsible": ^1.1.11
  "@radix-ui/react-dialog": ^1.1.14
  "@radix-ui/react-dropdown-menu": ^2.1.15
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-navigation-menu": ^1.2.13
  "@radix-ui/react-popover": ^1.1.14
  "@radix-ui/react-radio-group": ^1.3.7
  "@radix-ui/react-scroll-area": ^1.2.9
  "@radix-ui/react-select": ^2.2.4
  "@radix-ui/react-separator": ^1.1.7
  "@radix-ui/react-slider": ^1.3.5
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-tabs": ^1.1.12
  "@radix-ui/react-tooltip": ^1.2.7
  "@rainbow-me/rainbowkit": ^2.2.8
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
  "@tailwindcss/cli": ^4.1.4
  "@tailwindcss/typography": ^0.5.19
  "@tiptap/core": ^2.22.3
  "@tiptap/extension-link": ^2.22.3
  "@tiptap/extension-placeholder": ^2.22.3
  "@tiptap/extension-text-align": ^2.22.3
  "@tiptap/extension-text-style": ^2.22.3
  "@tiptap/extension-typography": ^2.22.3
  "@tiptap/extension-underline": ^2.22.3
  "@tiptap/pm": ^2.22.3
  "@tiptap/react": ^2.22.3
  "@tiptap/starter-kit": ^2.22.3
  "@vercel/analytics": ^1.5.0
  "animejs": ^4.0.2
  "class-variance-authority": ^0.7.1
  "clsx": ^2.1.1
  "cmdk": ^1.1.1
  "date-fns": ^4.1.0
  "date-fns-tz": ^3.2.0
  "lucide-react": ^0.488.0
  "next-themes": ^0.4.6
  "react-day-picker": ^9.7.0
  "react-markdown": ^10.1.0
  "recharts": ^2.15.3
  "remark-gfm": ^4.0.1
  "sonner": ^2.0.3
  "spacetime": ^7.10.0
  "tailwind-merge": ^3.2.0
  "tailwindcss": ^4.1.14
  "tw-animate-css": ^1.4.0
  "@tailwindcss/postcss": ^4.1.5
  "vaul": ^1.1.2
  "jotai": ^2.12.5
  "@t3-oss/env-nextjs": ^0.13.8
  "@sentry/nextjs": ^10.27.0
  "react-hook-form": ^7.59.0
  "@metamask/jazzicon": https://github.com/jmrossy/jazzicon#7a8df28
  "tsup": ^8.5.0
  "dompurify": ^3.3.0
  # BE
  "@apollo/client": ^3.13.9
  "@apollo/client-integration-nextjs": ^0.12.3
  "@graphql-codegen/add": ^6.0.0
  "@graphql-codegen/cli": ^5.0.2
  "@graphql-codegen/typescript": ^5.0.2
  "@graphql-codegen/typescript-apollo-client-helpers": ^3.0.0
  "@graphql-codegen/typescript-operations": ^5.0.2
  "@graphql-codegen/typescript-react-apollo": ^4.3.2
  "@mento-protocol/mento-sdk": ^1.15.5
  "graphql": ^16.11.0
  "pino-pretty": ^13.1.2
  # Shared
  "typescript": ^5.8.3
  "@ethersproject/address": ^5.8.0
  "@ethersproject/units": ^5.8.0
  "@hookform/resolvers": ^5.0.1
  "@tanstack/react-query": ^5.83.0
  "@turbo/gen": ^2.5.8
  "@types/node": ^22.14.1
  "@types/turndown": ^5.0.5
  "bignumber.js": ^9.3.0
  "concurrently": ^9.1.2
  "esbuild": ^0.25.0
  "eslint": ^9.31.0
  "@eslint/js": ^9.32.0
  "esbuild-plugin-preserve-directives": ^0.0.11
  "eslint-config-prettier": ^10.1.2
  "eslint-config-turbo": ^2.5.1
  "eslint-plugin-only-warn": ^1.1.0
  "eslint-plugin-react": ^7.37.5
  "eslint-plugin-react-hooks": ^5.2.0
  "typescript-eslint": ^8.38.0
  "globals": ^16.0.0
  "knip": ^5.64.3
  "postcss": ^8.5.3
  "prettier": ^3.5.3
  "prettier-plugin-tailwindcss": ^0.6.11
  "turbo": ^2.5.6
  "turndown": ^7.2.0
  "zod": ^4.1.12
  "dotenv": ^17.2.3
  "ethers": ^5.8.0
  "wagmi": ^2.16.9
  "viem": ^2.37.11
