packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/js": ^9.39.2
  "@mento-protocol/mento-sdk": ^1.19.0
  "@metamask/jazzicon": github:jmrossy/jazzicon#7a8df28
  "@rainbow-me/rainbowkit": ^2.2.10
  "@sentry/nextjs": ^10.36.0
  "@t3-oss/env-nextjs": ^0.13.10
  "@tailwindcss/postcss": ^4.1.18
  "@tanstack/react-query": ^5.90.20
  "@types/node": ^25.0.3
  "@types/react": ^19.2.9
  "@types/react-dom": ^19.2.3
  "@vercel/analytics": ^1.6.1
  concurrently: ^9.2.1
  esbuild-plugin-preserve-directives: ^0.0.11
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  ethers: ^5.7.2
  jotai: ^2.16.2
  lucide-react: ^0.563.0
  next: ^16.1.1
  next-themes: ^0.4.6
  pino-pretty: ^13.1.3
  postcss: ^8.5.6
  react: ^19.2.3
  react-dom: ^19.2.3
  react-hook-form: ^7.71.1
  sonner: ^2.0.7
  tailwindcss: ^4.1.18
  tsup: ^8.5.1
  typescript: ^5.9.3
  typescript-eslint: ^8.53.1
  viem: ^2.45.0
  wagmi: ^2.16.9
  zod: ^4.3.6

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js-pure
  - esbuild
  - sharp
