packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js-pure
  - esbuild
  - sharp

catalog:
  # FE
  "react": ^19.1.0
  "react-dom": ^19.1.0
  "next": ^15.5.9
  "@rainbow-me/rainbowkit": ^2.2.8
  "@types/react": ^19.1.2
  "@types/react-dom": ^19.1.2
  "@vercel/analytics": ^1.5.0
  "lucide-react": ^0.562.0
  "next-themes": ^0.4.6
  "sonner": ^2.0.3
  "tailwindcss": ^4.1.14
  "@tailwindcss/postcss": ^4.1.5
  "jotai": ^2.12.5
  "@t3-oss/env-nextjs": ^0.13.10
  "@sentry/nextjs": ^10.32.1
  "react-hook-form": ^7.69.0
  "@metamask/jazzicon": https://github.com/jmrossy/jazzicon#7a8df28
  "tsup": ^8.5.0
  # BE
  "@mento-protocol/mento-sdk": ^1.19.0
  "pino-pretty": ^13.1.2
  # Shared
  "typescript": ^5.8.3
  "@tanstack/react-query": ^5.83.0
  "@types/node": ^22.14.1
  "concurrently": ^9.1.2
  "eslint": ^9.39.2
  "@eslint/js": ^9.39.2
  "esbuild-plugin-preserve-directives": ^0.0.11
  "eslint-config-prettier": ^10.1.2
  "typescript-eslint": ^8.50.0
  "postcss": ^8.5.6
  "zod": ^4.2.1
  "ethers": ^5.8.0
  "wagmi": ^2.16.9
  "viem": ^2.43.3
