import type { PatternRegistry } from "./types";
import { createPattern } from "./base-pattern";
import {
  getAddressNameFromCache,
  getContractInfo,
} from "../../services/address-resolver-service";

const BROKER_PROXY_ADDRESS = "0x777a8255ca72412f0d706dc03c9d1987306b4cad";

/**
 * Known BiPoolManager exchange IDs mapped to human-readable pool names
 * These are generated by keccak256(abi.encodePacked(asset0.symbol(), asset1.symbol(), pricingModule.name()))
 */
const EXCHANGE_ID_TO_POOL_NAME: Record<string, string> = {
  // MGP-18 retained V2 exchanges
  "0xd580d237231109e6a96d67d82450611c610a805a26660c90281bdc0cd04a95c7":
    "USDm/AUDm",
  "0x517ccc3bcab9f35e2e24143a0c1809068efc649f740846cfb6a1c5703735c1ee":
    "USDm/CADm",
  "0x4206e101b13bf29e40b2bfed4cf167271c41677720f2ee786ac1bf5efac101cb":
    "USDm/ZARm",
  "0x1c9378bd0973ff313a599d3effc654ba759f8ccca655ab6d6ce5bd39a212943b":
    "USDm/COPm",
  "0xd11d52b973ddbb983cc2087aabcafd915fc3140cf9996aacc61db9710d1bde05":
    "USDm/BRLm",
  "0x7952984d7278ca3417febf52815c321984ac3147ced2c02bb6a02b0bcab08413":
    "USDm/PHPm",
  "0x3562f9d29eba092b857480a82b03375839c752346b9ebe93a57ab82410328187":
    "USDm/GHSm",
  "0x67a5122dab72931be57196e0abba81690461f327bc60fb98ca7eef0ac58906cc":
    "USDm/NGNm",
  "0x89de88b8eb790de26f4649f543cb6893d93635c728ac857f0926e842fb0d298b":
    "USDm/KESm",
  "0xc9664df358594c5eaf2f410ab371e2deb8b532ca26162d2bc36d99b8d174567b":
    "USDm/XOFm",

  // USDm pools
  "0xacc988382b66ee5456086643dcfd9a5ca43dd8f428f6ef22503d8b8013bcffd7":
    "USDm/USDC",
  "0x0d739efbfc30f303e8d1976c213b4040850d1af40f174f4169b846f6fd3d2f20":
    "USDm/axlUSDC",
  "0x773bcec109cee923b5e04706044fd9d6a5121b1a6a4c059c36fdbe5b845d4e9b":
    "USDm/USDT",
  // CELO pools (constant product)
  "0xcd96e577dd7336f4fbe75be98d0ba77fc33c9f0e97a0e1af7bb8e7c3c0f65a06":
    "USDm/CELO",
  "0xf4a2eb7e5c28a0e3cd1b3913ccbabb6c5413801ddc823b87b8b12c1e36f57e44":
    "EURm/CELO",
  "0x6f3402e0a69e50c7a61b4039c7ae5b8164a12c8b5e4d619e5698dc15c54f7ada":
    "BRLm/CELO",
  "0x832f8981c8eb9d0777ba77b4beb8c59e3be4a26b9f8bc4dcfe9d8e7b0e07c736":
    "XOFm/CELO",
  "0x45a1a6b5ac54f6e69b3ccc6fdfb6dae8f9eb6dbcd9a10ccf25ef8b8bf6f2f9da":
    "KESm/CELO",
};

/**
 * Get pool name from exchange ID, or return truncated ID if unknown
 */
function getPoolName(exchangeId: string): string {
  const normalized = exchangeId.toLowerCase();
  return (
    EXCHANGE_ID_TO_POOL_NAME[normalized] || `pool ${exchangeId.slice(0, 10)}...`
  );
}

/**
 * Format a FixidityLib value as a percentage
 * FixidityLib uses 1e24 as the fixed point multiplier (1.0 = 1e24)
 * @param value - The raw FixidityLib value
 * @returns Formatted percentage string (e.g., "0.05%")
 */
function formatFixidityAsPercentage(value: bigint | string | number): string {
  const numValue = BigInt(value);
  // FixidityLib: 1e24 = 100%
  // To get percentage: (value / 1e24) * 100
  // We use BigInt math to avoid precision loss, then convert to number for formatting
  const percentageScaled = (numValue * 10000n) / 10n ** 24n;
  const percentage = Number(percentageScaled) / 100;

  // Format with appropriate decimal places
  if (percentage === Math.floor(percentage)) {
    return `${percentage}%`;
  }
  return `${percentage.toFixed(2)}%`;
}

export const protocolPatterns: PatternRegistry = {
  "configureTradingLimit(bytes32,address,tuple)": createPattern(
    (contract, args) => {
      if (contract.address.toLowerCase() !== BROKER_PROXY_ADDRESS) {
        return null;
      }

      const [exchangeId, token, config] = args;
      const poolName = getPoolName(String(exchangeId!.value));
      const tokenAddress = String(token!.value);
      const tokenName =
        getContractInfo(tokenAddress)?.symbol ||
        getAddressNameFromCache(tokenAddress);
      const tradingLimitConfig = parseTradingLimitConfig(String(config!.value));

      if (tradingLimitConfig?.flags === "0") {
        return `Reset trading limits for ${tokenName} on ${poolName} pool`;
      }

      if (tradingLimitConfig?.flags === "4") {
        return `Set global trading limit for ${tokenName} on ${poolName} pool to ${formatInteger(tradingLimitConfig.limitGlobal)} whole tokens`;
      }

      return `Configure trading limits for ${tokenName} on ${poolName} pool`;
    },
    3,
    "configureTradingLimit",
  ),

  // BiPoolManager functions
  "setSpread(bytes32,uint256)": createPattern(
    (_contract, args) => {
      const [exchangeId, spread] = args;
      const poolName = getPoolName(String(exchangeId!.value));
      const spreadValue = spread!.value;
      if (typeof spreadValue === "boolean") {
        return `Set spread on ${poolName} pool`;
      }
      const spreadPercentage = formatFixidityAsPercentage(spreadValue);
      return `Set spread on ${poolName} pool to ${spreadPercentage}`;
    },
    2,
    "setSpread",
  ),

  "destroyExchange(bytes32,uint256)": createPattern(
    (_contract, args) => {
      const [exchangeId] = args;
      const poolName = getPoolName(String(exchangeId!.value));
      return `Destroy ${poolName} pool`;
    },
    2,
    "destroyExchange",
  ),
};

interface TradingLimitConfig {
  limitGlobal: string;
  flags: string;
}

function parseTradingLimitConfig(value: string): TradingLimitConfig | null {
  try {
    const parsed = JSON.parse(value) as Record<string, unknown>;
    if (
      typeof parsed.limitGlobal !== "string" ||
      typeof parsed.flags !== "string"
    ) {
      return null;
    }

    return {
      limitGlobal: parsed.limitGlobal,
      flags: parsed.flags,
    };
  } catch {
    return null;
  }
}

function formatInteger(value: string): string {
  return value.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
