import type { PatternRegistry } from "./types";
import { createPattern } from "./base-pattern";

/**
 * Known BiPoolManager exchange IDs mapped to human-readable pool names
 * These are generated by keccak256(abi.encodePacked(asset0.symbol(), asset1.symbol(), pricingModule.name()))
 */
const EXCHANGE_ID_TO_POOL_NAME: Record<string, string> = {
  // USDm pools
  "0xacc988382b66ee5456086643dcfd9a5ca43dd8f428f6ef22503d8b8013bcffd7":
    "USDm/USDC",
  "0x0d739efbfc30f303e8d1976c213b4040850d1af40f174f4169b846f6fd3d2f20":
    "USDm/axlUSDC",
  "0x773bcec109cee923b5e04706044fd9d6a5121b1a6a4c059c36fdbe5b845d4e9b":
    "USDm/USDT",
  // CELO pools (constant product)
  "0xcd96e577dd7336f4fbe75be98d0ba77fc33c9f0e97a0e1af7bb8e7c3c0f65a06":
    "USDm/CELO",
  "0xf4a2eb7e5c28a0e3cd1b3913ccbabb6c5413801ddc823b87b8b12c1e36f57e44":
    "EURm/CELO",
  "0x6f3402e0a69e50c7a61b4039c7ae5b8164a12c8b5e4d619e5698dc15c54f7ada":
    "BRLm/CELO",
  "0x832f8981c8eb9d0777ba77b4beb8c59e3be4a26b9f8bc4dcfe9d8e7b0e07c736":
    "XOFm/CELO",
  "0x45a1a6b5ac54f6e69b3ccc6fdfb6dae8f9eb6dbcd9a10ccf25ef8b8bf6f2f9da":
    "KESm/CELO",
};

/**
 * Get pool name from exchange ID, or return truncated ID if unknown
 */
function getPoolName(exchangeId: string): string {
  const normalized = exchangeId.toLowerCase();
  return (
    EXCHANGE_ID_TO_POOL_NAME[normalized] || `pool ${exchangeId.slice(0, 10)}...`
  );
}

/**
 * Format a FixidityLib value as a percentage
 * FixidityLib uses 1e24 as the fixed point multiplier (1.0 = 1e24)
 * @param value - The raw FixidityLib value
 * @returns Formatted percentage string (e.g., "0.05%")
 */
function formatFixidityAsPercentage(value: bigint | string | number): string {
  const numValue = BigInt(value);
  // FixidityLib: 1e24 = 100%
  // To get percentage: (value / 1e24) * 100
  // We use BigInt math to avoid precision loss, then convert to number for formatting
  const percentageScaled = (numValue * 10000n) / 10n ** 24n;
  const percentage = Number(percentageScaled) / 100;

  // Format with appropriate decimal places
  if (percentage === Math.floor(percentage)) {
    return `${percentage}%`;
  }
  return `${percentage.toFixed(2)}%`;
}

export const protocolPatterns: PatternRegistry = {
  // BiPoolManager functions
  "setSpread(bytes32,uint256)": createPattern(
    (_contract, args) => {
      const [exchangeId, spread] = args;
      const poolName = getPoolName(String(exchangeId!.value));
      const spreadValue = spread!.value;
      if (typeof spreadValue === "boolean") {
        return `Set spread on ${poolName} pool`;
      }
      const spreadPercentage = formatFixidityAsPercentage(spreadValue);
      return `Set spread on ${poolName} pool to ${spreadPercentage}`;
    },
    2,
    "setSpread",
  ),

  "destroyExchange(bytes32,uint256)": createPattern(
    (_contract, args) => {
      const [exchangeId] = args;
      const poolName = getPoolName(String(exchangeId!.value));
      return `Destroy ${poolName} pool`;
    },
    2,
    "destroyExchange",
  ),
};
