#!/usr/bin/env bash
# Installs workspace dependencies at the start of a Claude Code cloud session.
#
# Cloud sessions start from a fresh clone with no node_modules. The cloud
# environment's setup script cannot do this install: it runs before Claude Code
# launches and before the repository is cloned, so the working tree does not
# exist yet. This hook runs after the clone, so it is the right place for any
# step that needs repository files.
#
# Local sessions exit immediately.
set -uo pipefail

if [[ ${CLAUDE_CODE_REMOTE-} != "true" ]]; then
	exit 0
fi

repository_root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}"
if [[ -z ${repository_root} ]] || [[ ! -f "${repository_root}/package.json" ]]; then
	echo "cloud-session-setup: no repository root found, skipping install" >&2
	exit 0
fi

cd "${repository_root}" || exit 0

# Trunk fetches its plugin bundle from a github.com archive URL, and the cloud
# session's GitHub gateway refuses that with HTTP 403 no matter what the network
# allowlist says, so `trunk check` and `trunk fmt` exit before linting anything.
# The git protocol is not intercepted, so a clone of the same bundle at the same
# ref works, and `.trunk/user.yaml` points Trunk at that checkout.
#
# user.yaml rather than `.trunk/trunk.yaml`, the other file that can carry a
# plugin source: user.yaml is already gitignored, so the workaround leaves the
# tree clean and cannot be committed by accident.
#
# The same file disables trunk-check-all-pre-push. That action runs
# `trunk check --all`, which cannot pass in a cloud session -- markdown-link-check
# reaches no github.com link and trufflehog verifies every pinned action SHA
# through the proxy -- so it blocks every push after several minutes of linting.
# The pre-push actions that do pass here (check-types, knip, the ADR reminder)
# stay enabled, so a push is still gated on real checks.
configure_trunk_for_cloud_session() {
	local trunk_config=".trunk/trunk.yaml"
	local user_config=".trunk/user.yaml"
	local marker="# generated by scripts/cloud-session-setup.sh"

	[[ -f ${trunk_config} ]] || return 0

	# user.yaml is a personal override file. Leave one this script did not write
	# alone, so a hand-edited override is never silently replaced.
	if [[ -f ${user_config} ]] && ! grep -qF "${marker}" "${user_config}"; then
		echo "cloud-session-setup: ${user_config} was not generated here, leaving it alone"
		return 0
	fi

	# Take the ref from trunk.yaml so the checkout cannot drift from the bundle the
	# repository pins. `local` makes Trunk ignore `ref`, so a mismatched clone would
	# lint against a different plugin version than CI does, with nothing to show it.
	local ref
	ref="$(sed -n 's/^[[:space:]]*ref:[[:space:]]*\([^[:space:]]*\).*/\1/p' "${trunk_config}" | head -1)"
	if [[ -z ${ref} ]]; then
		echo "cloud-session-setup: no plugin ref in ${trunk_config}, skipping trunk setup"
		rm -f "${user_config}"
		return 0
	fi

	# Keying the path on the ref makes a moved pin clone afresh rather than reuse a
	# checkout of the bundle before it.
	local clone_directory="${TMPDIR:-/tmp}/trunk-plugins-${ref}"
	local clone_log="${TMPDIR:-/tmp}/cloud-session-trunk-clone.log"
	if [[ ! -d "${clone_directory}/.git" ]]; then
		rm -rf "${clone_directory}"
		# An ordinary checkout, not --bare: Trunk reads plugin.yaml from the working
		# tree, and a bare clone fails with `expected plugin.yaml to be present`.
		if ! timeout 120 git clone --quiet --depth 1 --branch "${ref}" \
			https://github.com/trunk-io/plugins "${clone_directory}" >"${clone_log}" 2>&1; then
			rm -rf "${clone_directory}"
			# Drop a stale generated override as well. Pointing Trunk at a directory
			# that no longer exists fails with a config error about the path, which
			# buries the real cause; with no override it fails with the 403 instead.
			rm -f "${user_config}"
			echo "cloud-session-setup: could not clone the trunk plugin bundle at ${ref}, so trunk will not run (log: ${clone_log})"
			return 0
		fi
	fi

	cat >"${user_config}" <<-EOF
		${marker}
		version: 0.1
		plugins:
		  sources:
		    - id: trunk
		      local: ${clone_directory}
		actions:
		  disabled:
		    - trunk-check-all-pre-push
	EOF
	echo "cloud-session-setup: trunk plugins at ${ref} ready, trunk-check-all-pre-push disabled"
}

configure_trunk_for_cloud_session

# The image ships one chromium build under PLAYWRIGHT_BROWSERS_PATH, and the
# Playwright the workspace installs wants a specific, usually newer revision, so
# `launch()` fails with `Executable doesn't exist`. Running `playwright install`
# is not the answer: it re-downloads a browser on every session.
#
# Alias each wanted revision onto the shipped build instead. More than one can be
# wanted at a time, because workspaces pin different Playwright versions, so this
# walks every installed copy rather than assuming a single revision. It only ever
# creates a revision directory that does not already exist, so a real browser
# install is never shadowed.
#
# The alias is an approximation, not the pinned browser: it makes the shipped
# build answer at the wanted revision's path, so Playwright starts and drives it,
# but the binary is still the older one. Good enough to run and debug a suite;
# not authoritative for pixel comparisons. CI does not rely on any of this -- the
# Playwright jobs run inside the pinned mcr.microsoft.com/playwright container --
# so the approximation never reaches Argos baselines or a required check.
#
# Installing the real revision would be better and is what this defers to: an
# existing directory is left alone, so once `npx playwright install` can fetch it
# the true build wins automatically. Today it cannot -- cdn.playwright.dev is not
# on the session's network allowlist and the download is refused with HTTP 403.
#
# If a future Playwright changes the path it looks for, the alias is simply not
# where it looks and `launch()` reports the path it wanted, which names the fix.
configure_playwright_browser_aliases() {
	local browsers_root="${PLAYWRIGHT_BROWSERS_PATH-}"
	[[ -n ${browsers_root} ]] || return 0
	[[ -d ${browsers_root} ]] && [[ -w ${browsers_root} ]] || return 0

	# Find the shipped builds by their binaries rather than by assuming a layout:
	# the directory names differ between the revision the image ships and the ones
	# Playwright asks for now (`chrome-linux` became `chrome-linux64`, and
	# `headless_shell` became `chrome-headless-shell`).
	local shipped_chrome shipped_shell
	shipped_chrome="$(find "${browsers_root}" -maxdepth 3 -type f -name chrome -path '*chromium-*' 2>/dev/null | head -1)"
	shipped_shell="$(find "${browsers_root}" -maxdepth 3 -type f \
		\( -name headless_shell -o -name chrome-headless-shell \) 2>/dev/null | head -1)"
	[[ -n ${shipped_chrome} ]] || [[ -n ${shipped_shell} ]] || return 0

	local created="" manifest revisions name revision alias_directory
	for manifest in node_modules/.pnpm/playwright-core@*/node_modules/playwright-core/browsers.json; do
		[[ -f ${manifest} ]] || continue
		revisions="$(node -e '
			const fs = require("fs");
			const manifest = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
			for (const browser of manifest.browsers) {
				if (browser.name === "chromium" || browser.name === "chromium-headless-shell") {
					console.log(browser.name, browser.revision);
				}
			}
		' "${manifest}" 2>/dev/null)"
		[[ -n ${revisions} ]] || continue
		while read -r name revision; do
			case ${name} in
			chromium)
				[[ -n ${shipped_chrome} ]] || continue
				alias_directory="${browsers_root}/chromium-${revision}"
				[[ -e ${alias_directory} ]] && continue
				mkdir -p "${alias_directory}"
				ln -s "$(dirname "${shipped_chrome}")" "${alias_directory}/chrome-linux64"
				;;
			chromium-headless-shell)
				[[ -n ${shipped_shell} ]] || continue
				alias_directory="${browsers_root}/chromium_headless_shell-${revision}"
				[[ -e ${alias_directory} ]] && continue
				mkdir -p "${alias_directory}/chrome-headless-shell-linux64"
				ln -s "${shipped_shell}" "${alias_directory}/chrome-headless-shell-linux64/chrome-headless-shell"
				;;
			*)
				continue
				;;
			esac
			created="${created} ${name}@${revision}"
		done <<<"${revisions}"
	done

	if [[ -n ${created} ]]; then
		echo "cloud-session-setup: aliased playwright browsers onto the shipped build (approximate, not the pinned revision):${created}"
	fi
}

# Every exit below runs the browser aliasing first: it reads the Playwright
# revisions out of node_modules, so it has to follow the install rather than sit
# beside the trunk setup above.
finish() {
	configure_playwright_browser_aliases
	exit 0
}

# The environment provides its own pnpm; package.json pins the one this
# workspace expects. Read both before the fast path below, so a revision that
# moves only the pin is still reported and still reinstalls.
pinned_pnpm="$(sed -n 's/.*"packageManager"[[:space:]]*:[[:space:]]*"pnpm@\([^"]*\)".*/\1/p' package.json)"
running_pnpm="$(pnpm --version 2>/dev/null)"
if [[ -n ${pinned_pnpm} ]] && [[ ${running_pnpm} != "${pinned_pnpm}" ]]; then
	echo "cloud-session-setup: pnpm ${running_pnpm:-not found} does not match the pinned pnpm@${pinned_pnpm}"
fi

# pnpm creates node_modules/.pnpm before it links anything, so that directory
# exists even after a failed install and cannot stand in for success. Gate on a
# stamp this script writes itself, so a partial tree is retried rather than
# mistaken for a finished install.
#
# The stamp records every input that decides the tree: the lockfile, the pnpm
# that installs it, and the configuration that shapes the layout. `.npmrc`
# carries this workspace's `public-hoist-pattern` entries and
# `pnpm-workspace.yaml` its `onlyBuiltDependencies`, and either can move on a
# pull or a branch switch without the lockfile moving, so a resumed session
# reinstalls instead of running against a tree laid out for the previous
# revision. An unreadable lockfile digest stays empty and never matches, so the
# uncertain case reinstalls too.
stamp_file="node_modules/.cloud-session-setup-complete"
lockfile_digest="$(sha256sum pnpm-lock.yaml 2>/dev/null | cut -d' ' -f1)"
# Hash the per-file digests rather than the concatenated bytes: each line names
# its file, so a file that is absent is distinguishable from one whose content
# moved into its neighbour.
config_digest="$(sha256sum pnpm-workspace.yaml .npmrc 2>/dev/null | sha256sum | cut -d' ' -f1)"
# Record the pnpm that actually ran the install, not the one package.json asks
# for. Stamping the pin would certify a tree built by a different binary as if
# the pinned version had produced it, and the stamp would keep matching after
# the environment is corrected — so the wrong tree would never be rebuilt. The
# pin is recorded alongside it so a revision that moves only the pin still
# reinstalls.
stamp_expected="${lockfile_digest} ${config_digest} pnpm@${running_pnpm:-none} pin@${pinned_pnpm}"
stamp_actual=""
if [[ -f ${stamp_file} ]]; then
	read -r stamp_actual <"${stamp_file}"
fi
if [[ -n ${lockfile_digest} ]] && [[ ${stamp_actual} == "${stamp_expected}" ]]; then
	echo "cloud-session-setup: dependencies already installed"
	finish
fi

# Drop the stamp before pnpm touches node_modules. An install that fails partway
# has already changed the tree, and a stamp left over from the revision before
# it would otherwise match again after a switch back and skip the repair.
rm -f "${stamp_file}"

# The hook's output becomes session context, so keep the install log on disk and
# print only a summary. A cold install of this workspace runs for minutes, which
# is why the hook sets a 600 second timeout.
log_file="${TMPDIR:-/tmp}/cloud-session-setup.log"
echo "cloud-session-setup: running pnpm install --frozen-lockfile (log: ${log_file})"
if pnpm install --frozen-lockfile >"${log_file}" 2>&1; then
	printf '%s\n' "${stamp_expected}" >"${stamp_file}"
	echo "cloud-session-setup: dependencies installed"
	finish
fi

# Report the failure on stdout as well: only stdout reaches the session context,
# and an agent that cannot see the failure will read the empty node_modules as a
# repository problem instead of an install that never finished.
echo "cloud-session-setup: pnpm install FAILED; node_modules is incomplete."
echo "cloud-session-setup: builds, type checks and tests will not run until it succeeds."
echo "cloud-session-setup: last lines of ${log_file}:"
tail -20 "${log_file}"
finish
