name: Debug Deployment Status
on:
  deployment_status:

permissions:
  contents: read
  deployments: read
  id-token: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug deployment status
        run: |
          echo "=== Deployment Status Debug ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Deployment state: ${{ github.event.deployment_status.state }}"
          echo "Environment: ${{ github.event.deployment_status.environment }}"
          echo "Environment URL: ${{ github.event.deployment_status.environment_url }}"
          echo "Deployment ID: ${{ github.event.deployment_status.deployment.id }}"
          echo "Repository: ${{ github.event.deployment_status.repository.full_name }}"
          echo ""
          echo "=== Full Event Data ==="
          echo '${{ toJSON(github.event) }}'

          echo "=== Deployment Status Data ==="
          echo '${{ toJSON(github.event.deployment_status) }}'

          echo ""
          echo "=== URL Check Results ==="
          if [[ "${{ github.event.deployment_status.environment_url }}" == *"appmento"* ]]; then
            echo "✅ URL contains 'appmento'"
          else
            echo "❌ URL does NOT contain 'appmento'"
          fi

          if [[ "${{ github.event.deployment_status.environment_url }}" == *"app.mento.org"* ]]; then
            echo "✅ URL contains 'app.mento.org'"
          else
            echo "❌ URL does NOT contain 'app.mento.org'"
          fi
